# @url=http://localhost:3000
@url=https://matchmachine.credot-web.com

################################################################
GET {{url}}/api/echo

################################################################
POST {{url}}/api/login
Content-Type: application/json

{
    "account":"admin",
    "password":"123456"
}

##############
